AVAILABLE_FILE_FORMATS = (".xlsx")

INSTRUCTION_FILE_NAME = "example file with words.xlsx"
PATH_TO_INSTRUCTION_FILE = f"constants/files/{INSTRUCTION_FILE_NAME}"

MONTH_IN_SECOND = 2629800

SIMPLE_SUB_COST = 1
START_SUB_COST = 2
PRO_SUB_COST = 2.5

USD_CODE = 840

FREE_TERM_SUB_IN_DAYS = 3

SUBSCRIPTION_PERIOD = 3

TELEGRAM_BOT_LINK = "https://t.me/ClanityBot"
