"""Added user sessino

Revision ID: 1b5c560bc526
Revises: 36c577de4f65
Create Date: 2025-05-12 22:44:52.486104

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b5c560bc526"
down_revision: Union[str, None] = "36c577de4f65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_datetime", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userdata.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usersession_user_id"), "usersession", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usersession_user_id"), table_name="usersession")
    op.drop_table("usersession")
    op.drop_index(op.f("ix_userfile_user_id"), table_name="userfile")
    op.drop_table("userdata")
    # ### end Alembic commands ###
