"""Added subscription levels

Revision ID: 61e50da66b40
Revises: 89ae6effb6ca
Create Date: 2025-05-15 14:32:37.412717
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61e50da66b40'
down_revision: Union[str, None] = '89ae6effb6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subscription_enum = sa.Enum(
    'NON_SUBSCRIPTION', 'SIMPLE', 'START', 'PRO',
    name='usersubscriptionlevels'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'userdata',
        sa.Column('subscription_level', subscription_enum, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'subscription_level')

    subscription_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
