"""Added free term sub

Revision ID: 3ef3f0432643
Revises: 71e4fec78c0e
Create Date: 2025-05-16 12:23:37.577609

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ef3f0432643"
down_revision: Union[str, None] = "71e4fec78c0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# SELECT enumlabel
# FROM pg_enum
# JOIN pg_type ON pg_enum.enumtypid = pg_type.oid
# WHERE pg_type.typname = 'usersubscriptionlevels'
# ORDER BY enumsortorder;


def upgrade():
    op.execute(
        f"ALTER TYPE usersubscriptionlevels ADD VALUE IF NOT EXISTS 'FREE_TERM';"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
