"""Added chat id

Revision ID: 89ae6effb6ca
Revises: 1b5c560bc526
Create Date: 2025-05-13 00:40:57.005926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector



# revision identifiers, used by Alembic.
revision: str = '89ae6effb6ca'
down_revision: Union[str, None] = '1b5c560bc526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersession', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_usersession_chat_id'), 'usersession', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_chat_id'), table_name='usersession')
    op.drop_column('usersession', 'chat_id')
    # ### end Alembic commands ###
