"""Added models

Revision ID: 92242e343f6f
Revises: 
Create Date: 2025-04-30 21:57:06.966485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector



# revision identifiers, used by Alembic.
revision: str = '92242e343f6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_userdata_user_id'), 'userdata', ['user_id'], unique=False)
    op.create_table('userfile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_userfile_user_id'), 'userfile', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfile_user_id'), table_name='userfile')
    op.drop_table('userfile')
    op.drop_index(op.f('ix_userdata_user_id'), table_name='userdata')
    op.drop_table('userdata')
    # ### end Alembic commands ###
