"""Add purchase

Revision ID: 36c577de4f65
Revises: 92242e343f6f
Create Date: 2025-05-06 01:14:25.683092

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36c577de4f65'
down_revision: Union[str, None] = '92242e343f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchaseregistry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_datetime', sa.DateTime(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchaseregistry_user_id'), 'purchaseregistry', ['user_id'], unique=False)
    op.add_column('userfile', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userfile', 'userdata', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfile', type_='foreignkey')
    op.drop_column('userfile', 'id')
    op.drop_index(op.f('ix_purchaseregistry_user_id'), table_name='purchaseregistry')
    op.drop_table('purchaseregistry')
    # ### end Alembic commands ###
