"""Add username to userdata

Revision ID: 1fcb8c9962f0
Revises: 92cac410b842
Create Date: 2025-05-16 13:38:24.462908

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1fcb8c9962f0'
down_revision: Union[str, None] = '92cac410b842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'username')
    # ### end Alembic commands ###
