"""Added subscription datetime

Revision ID: 92cac410b842
Revises: 3ef3f0432643
Create Date: 2025-05-16 13:02:06.258992

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92cac410b842"
down_revision: Union[str, None] = "3ef3f0432643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userdata", sa.Column("subscription_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userdata", "subscription_date")
    # ### end Alembic commands ###
