"""Added user id as bigint

Revision ID: 71e4fec78c0e
Revises: 61e50da66b40
Create Date: 2025-05-15 15:11:27.749253

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71e4fec78c0e'
down_revision: Union[str, None] = '61e50da66b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchaseregistry', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('userdata', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('userdata', 'subscription_level',
                    existing_type=postgresql.ENUM('NON_SUBSCRIPTION', 'SIMPLE', 'START', 'PRO', 'FREE_TERM',
                                                  name='usersubscriptionlevels'),
                    nullable=True)
    op.drop_index('ix_userdata_user_id', table_name='userdata')
    op.create_index(op.f('ix_userdata_user_id'), 'userdata', ['user_id'], unique=True)
    op.alter_column('userfile', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.drop_constraint('userfile_user_id_fkey', 'userfile', type_='foreignkey')
    op.create_foreign_key(None, 'userfile', 'userdata', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('usersession', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    nullable=True)
    op.alter_column('usersession', 'chat_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    nullable=True)
    op.drop_constraint('usersession_user_id_fkey', 'usersession', type_='foreignkey')
    op.create_foreign_key(None, 'usersession', 'userdata', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersession', type_='foreignkey')
    op.create_foreign_key('usersession_user_id_fkey', 'usersession', 'userdata', ['user_id'], ['user_id'])
    op.alter_column('usersession', 'chat_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('usersession', 'user_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint(None, 'userfile', type_='foreignkey')
    op.create_foreign_key('userfile_user_id_fkey', 'userfile', 'userdata', ['user_id'], ['user_id'])
    op.alter_column('userfile', 'user_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_userdata_user_id'), table_name='userdata')
    op.create_index('ix_userdata_user_id', 'userdata', ['user_id'], unique=False)
    op.alter_column('userdata', 'subscription_level',
                    existing_type=postgresql.ENUM('NON_SUBSCRIPTION', 'SIMPLE', 'START', 'PRO',
                                                  name='usersubscriptionlevels'),
                    nullable=False)
    op.alter_column('userdata', 'user_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('purchaseregistry', 'user_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
